//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRChatContentPublisher.CrashHandler.App.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VRChatContentPublisher.CrashHandler.App.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VRChat Content Publisher - Crash Handler.
        /// </summary>
        internal static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VRChat Content Publisher has crashed.
        /// </summary>
        internal static string CrashReport_Title {
            get {
                return ResourceManager.GetString("CrashReport_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Details are provided below..
        /// </summary>
        internal static string CrashReport_Subtitle {
            get {
                return ResourceManager.GetString("CrashReport_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please report this issue to help us improve the app..
        /// </summary>
        internal static string CrashReport_ReportHeader {
            get {
                return ResourceManager.GetString("CrashReport_ReportHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please attach log file when report, log file MAY contains sensitive information (e.g User name, Blueprint ID)..
        /// </summary>
        internal static string CrashReport_ReportTip {
            get {
                return ResourceManager.GetString("CrashReport_ReportTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Logs Folder.
        /// </summary>
        internal static string CrashReport_OpenLogsFolder {
            get {
                return ResourceManager.GetString("CrashReport_OpenLogsFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Join QQ Group.
        /// </summary>
        internal static string CrashReport_JoinQQGroup {
            get {
                return ResourceManager.GetString("CrashReport_JoinQQGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Join via link.
        /// </summary>
        internal static string CrashReport_JoinViaLink {
            get {
                return ResourceManager.GetString("CrashReport_JoinViaLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Report on Github.
        /// </summary>
        internal static string CrashReport_ReportOnGithub {
            get {
                return ResourceManager.GetString("CrashReport_ReportOnGithub", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close and Restart App.
        /// </summary>
        internal static string CrashReport_CloseAndRestart {
            get {
                return ResourceManager.GetString("CrashReport_CloseAndRestart", resourceCulture);
            }
        }
    }
}
